development:
  access_key_id: AKIAJTN2EZPPE6I2ROZA
  secret_access_key: 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

test:
  access_key_id: abc
  secret_access_key: abc/efg

production:
  access_key_id: AKIAJTN2EZPPE6I2ROZA
  secret_access_key: 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
